export default [
    {
      courseName: "DeepLearning.A ...",
      courseId: "1675437",
      provider: "LinkedIn",
      singer: "Viktoria Strušnik",
      describe: "Launch Your Career in Marke...",
      status: "Active",
    },{
        courseName: "DeepLearning.A ...",
        courseId: "2675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      }
      ,{
        courseName: "DeepLearning.A ...",
        courseId: "3675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "4675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "5675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "6675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },
      {
        courseName: "DeepLearning.A ...",
        courseId: "1675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
          courseName: "DeepLearning.A ...",
          courseId: "2675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        }
        ,{
          courseName: "DeepLearning.A ...",
          courseId: "3675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "4675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "5675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "6675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
          courseName: "DeepLearning.A ...",
          courseId: "8675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },
        {
          courseName: "DeepLearning.A ...",
          courseId: "1675437",
          provider: "LinkedIn",
          singer: "Viktoria Strušnik",
          describe: "Launch Your Career in Marke...",
          status: "Active",
        },{
            courseName: "DeepLearning.A ...",
            courseId: "2675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          }
          ,{
            courseName: "DeepLearning.A ...",
            courseId: "3675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "4675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "5675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "6675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },{
            courseName: "DeepLearning.A ...",
            courseId: "8675437",
            provider: "LinkedIn",
            singer: "Viktoria Strušnik",
            describe: "Launch Your Career in Marke...",
            status: "Active",
          },
          
]