export default [
    {
      courseName: "DeepLearning.A ...",
      courseId: "8675437",
      provider: "LinkedIn",
      singer: "Viktoria Strušnik",
      describe: "Launch Your Career in Marke...",
      status: "Active",
    },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      }
      ,{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      },{
        courseName: "DeepLearning.A ...",
        courseId: "8675437",
        provider: "LinkedIn",
        singer: "Viktoria Strušnik",
        describe: "Launch Your Career in Marke...",
        status: "Active",
      }
]